#!/usr/bin/env bash
BOOK=${1?"missing book name ..."}
JAWIKI=https://ja.wikisource.org/wiki
GETBWSK=$HOME/jafiction2wspa/getbwsk.js
GETLINK=$HOME/jafiction2wspa/getlinks.js
DECODEURI=$HOME/jafiction2wspa/decodeURI
BOOKLINK=$JAWIKI/$BOOK
[ -d $BOOK ] || mkdir $BOOK
cd $BOOK
$GETLINK $BOOKLINK | $DECODEURI > link.txt
$GETBWSK $BOOKLINK | sed '/^Public domain/,$ d' > all.txt
