#!/usr/bin/env bash
AUTHOR=梶井基次郎
BOOK=$(pwd | sed 's#.*/\([^/]*\)#\1#')
#../prepare_coverparameters 
../mov_with 
../mk_text_subdir 
~/move2jatts 
cd ~/raylexlee.github.io/jatts
[ -f $AUTHOR.html ] || ./make_group_html.txt  $AUTHOR
csplit -n 1 $AUTHOR.html /index\.html/
./make_jatextapp_html.txt $BOOK >> xx0
cat xx1 >> xx0
rm xx1
mv xx0 $AUTHOR.html 
cd text/$BOOK
../../ja_trans_zh.txt 
cd $(pwd | sed 's/ja/zh/')
CURDIR=$(pwd)
cd ../..
[ -f $AUTHOR.html ] || ./make_group_html.txt  $AUTHOR
csplit -n 1 $AUTHOR.html /index\.html/
./make_zhtextapp_html.txt $BOOK >> xx0
cat xx1 >> xx0
rm xx1
mv xx0 $AUTHOR.html 
cd $CURDIR
for i in $(ls [0-9]*); do ~/mstts/zsp $i; done
