#!/usr/bin/env bash
BOOK=${1?"missing book name ..."}
BOOKLINK=${2?"missing link of book name ..."}
JAWIKI=https://ja.wikisource.org/wiki
#BOOKLINK=$JAWIKI/$BOOK
GETBWSK=$HOME/jafiction2wspa/getbwsk.js
GETLINK=$HOME/jafiction2wspa/getlinks.js
DECODEURI=$HOME/jafiction2wspa/decodeURI
[ -d $BOOK ] || mkdir $BOOK
cd $BOOK
$GETLINK $BOOKLINK | $DECODEURI > link.txt
$GETBWSK $BOOKLINK | sed -e 's#\.mw-par.*\}##g' -e '/^Public domain/,$ d' > converted.txt
