#!/usr/bin/env bash
[ -f xx001 ] && bash raylex.sh
[ -d text ] || mkdir text
for i in $(ls [0-9]*txt)
do
sed -e '/^\ *$/ d' -e 's#\[編集\]##' < $i > text/$i
done
sed 's#\[編集\]##' < coverparameters.txt > text/coverparameters.txt

