#awk '{print "./jws",$1,$2;}' < 夏目漱石.txt | sed 's#\([()]\)#\\\1#g' > 夏目漱石.sh
./jws 吾輩は猫である https://ja.wikisource.org/wiki/吾輩は猫である
./jws 坊っちゃん https://ja.wikisource.org/wiki/坊つちやん
./jws 倫敦塔 https://ja.wikisource.org/wiki/倫敦塔_\(小説\)
./jws 三四郎 https://ja.wikisource.org/wiki/三四郎
./jws こゝろ https://ja.wikisource.org/wiki/こゝろ
./jws 硝子戸の中 https://ja.wikisource.org/wiki/硝子戸の中
./jws 明暗 https://ja.wikisource.org/wiki/明暗
./jws ウィキペディア日本語版 https://ja.wikipedia.org/wiki/メインページ
./jws 夏目漱石 https://ja.wikipedia.org/wiki/夏目漱石
./jws 草枕 https://ja.wikisource.org/wiki/草枕
./jws 二百十日 https://ja.wikisource.org/wiki/二百十日_\(小説\)
./jws 野分 https://ja.wikisource.org/wiki/野分_\(小説\)
./jws 虞美人草 https://ja.wikisource.org/wiki/虞美人草
./jws 坑夫 https://ja.wikisource.org/wiki/坑夫
./jws それから https://ja.wikisource.org/wiki/それから
./jws 門 https://ja.wikisource.org/wiki/門_\(小説\)
./jws 彼岸過迄 https://ja.wikisource.org/wiki/彼岸過迄
./jws 行人 https://ja.wikisource.org/wiki/行人
./jws 道草 https://ja.wikisource.org/wiki/道草_\(小説\)
./jws 幻影の盾 https://ja.wikisource.org/wiki/幻影の盾
./jws 琴のそら音 https://ja.wikisource.org/wiki/琴のそら音
./jws 一夜 https://ja.wikisource.org/wiki/一夜
./jws 薤露行 https://ja.wikisource.org/wiki/薤露行
./jws 趣味の遺伝 https://ja.wikisource.org/wiki/趣味の遺伝
./jws 文鳥 https://ja.wikisource.org/wiki/文鳥
./jws 夢十夜 https://ja.wikisource.org/wiki/第三夜
./jws 永日小品 https://ja.wikisource.org/wiki/永日小品
./jws イズムの功過 https://ja.wikisource.org/wiki/イズムの功過
./jws 現代日本の開化 https://ja.wikisource.org/wiki/現代日本の開化
./jws 私の個人主義 https://ja.wikisource.org/wiki/私の個人主義
./jws 思い出す事など https://ja.wikisource.org/wiki/思い出す事など
